{{- if .Values.serviceSecrets }}
{{- $env_name := $.Values.envName }}
{{- $service_name := $.Values.serviceName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "http-service.fullname" . }}-secrets
spec:
  refreshInterval: {{ .Values.secretStoreRefreshInterval }}
  secretStoreRef:
    name: {{ .Release.Namespace }}-parameterstore
    kind: SecretStore
  target:
    name: {{ include "http-service.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range $key, $value := .Values.serviceSecrets }}
    - secretKey: {{ $key | upper | quote }}
      remoteRef:
        key: "/{{ $env_name }}/{{ $service_name }}/{{ $value }}"
    {{- end }}
{{- end }}
