apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "http-service.fullname" . }}-service-role
  annotations:
  {{- if .Values.irsaRoleArn }}
    "eks.amazonaws.com/role-arn": {{ .Values.irsaRoleArn }}
  {{- end }}
  labels:
    "app.kubernetes.io/name": {{ include "http-service.fullname" . }}-service-role